---
title: "Tidy Tuesday week 23"
author: "Erin Franke"
date: "6/2/2021"
header-includes:
  - \usepackage[font={small}]{caption}
output:
  html_document:
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load packages and read in the data
```{r}
library(tidytuesdayR)
library(readr)
library(survivoR)
library(tidyverse)
library(gridExtra)
summary <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/summary.csv')
challenges <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/challenges.csv')
castaways <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/castaways.csv')
viewers <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/viewers.csv')
jury_votes <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-01/jury_votes.csv')
```

**Question: Which states are the best at survivor? From states that have had at least 10 contestants compete in the 40 seasons, what proportion of those contestants have made it past the 10th round and what proportion have won?**

```{r}
#define impressive_performance, which indicates that the contestant has made it past the 10th round
castaways <- castaways %>%
  mutate(impressive_performance = result %in% c("11th voted out", "12th voted out", "13th voted out", "14th voted out", "15th voted out", "16th voted out", "17th voted out", "18th voted out", "2nd runner-up", "2nd Runner-up", "Co-runner-up", "Runner-up", "Sole Survivor"))

#find the number of contestants per state 
contestants_per_state <- castaways %>%
  group_by(state) %>%
  count()

#create bar plot showing distribution of contestants from each state
(plot1 <- contestants_per_state %>%
  mutate(greaterthan10 = n>10) %>%
  ggplot(aes(y=fct_reorder(state,n), x=n, fill=greaterthan10))+
  geom_col()+
  theme_minimal()+
  scale_x_continuous(expand = c(0,0)) +
  theme(plot.title.position = "plot", plot.title = element_text(size = 16))+
  labs(title = "Survivor contestants from each state (seasons 1-40)", x="", y="", fill = "number of contestants")+ 
  scale_fill_discrete(name = "number of contestants", labels = c("1-9", "10+")))

#find the number of contestants per state that made it past the 10th round
pastround10 <- castaways %>%
  group_by(state) %>%
  summarise(past10 = sum(impressive_performance))

#find the number of contestants per state that won
winners <- castaways %>%
  group_by(state) %>%
  summarise(won = sum(result == "Sole Survivor"))

#join the datasets by state and calculate proportions 
(joined <- contestants_per_state %>%
  full_join(pastround10, by = "state") %>%
  mutate(propimpressive = past10/n) %>%
  full_join(winners , by="state") %>%
  mutate(propwinning = won/n) %>%
  filter(n>=10))

#create plot showing the proportion of contestants from each state making it past round 10 and winning
(plot2 <- joined %>%
  ggplot(aes(y=fct_reorder(state, propimpressive), x=propimpressive)) +
  geom_col(aes(fill = "cadetblue4")) + 
  geom_col(aes(y=state, x=propwinning, fill = "darkgoldenrod3"))+
  theme_minimal() + 
  labs(title = "Breaking down Survivor performances for states with 10+ contestants", x = "proportion of state's contestants", y="") + 
  scale_x_continuous(expand = c(0,0)) + 
  theme(plot.title.position = "plot", plot.title = element_text(size = 16))+
  scale_fill_identity(name = "voted out?", breaks = c("cadetblue4", "darkgoldenrod3"), label = c("past round 10", "season's sole survivor"), guide = "legend"))
```

Arrange the plots side-by-side
```{r, fig.width=15, fig.cap= "Plot created by Erin Franke, data from survivoR package by Daniel Oehm", fig.}
grid.arrange(plot1, plot2, ncol = 2)
```




