---
title: "Tidy Tuesday Holiday Movies"
author: "Erin Franke"
date: "2023-12-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(showtext)
font_add_google("Gaegu")

holiday_movies <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-12-12/holiday_movies.csv')
holiday_movie_genres <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-12-12/holiday_movie_genres.csv')
```

```{r}
holiday_movies %>% 
  mutate(decade = case_when(year >= 1930 & year < 1940 ~ "1930s",
                            year >= 1940 & year < 1950 ~ "1940s",
                            year >= 1950 & year < 1960 ~ "1950s",
                            year >= 1960 & year < 1970 ~ "1960s",
                            year >= 1970 & year < 1980 ~ "1970s",
                            year >= 1980 & year < 1990 ~ "1980s",
                            year >= 1990 & year < 2000 ~ "1990s",
                            year >= 2000 & year < 2010 ~ "2000s",
                            year >= 2010 & year < 2020 ~ "2010s", 
                            year >= 2020 ~ "2020s"),
         img = "tree.png") %>%
  filter(num_votes >= 500) %>%
  group_by(decade) %>%
  mutate(max_rating = max(average_rating, na.rm = TRUE)) %>%
  filter(max_rating == average_rating) %>%
  mutate(most_votes = case_when(max(num_votes) != num_votes ~ 0,
                                TRUE ~ 1)) %>%  # two movies in 1960s with same rating - take one with higher number of votes
  filter(most_votes == 1) %>%
  mutate(primary_title_2 = paste0(primary_title, " (", runtime_minutes, " min)")) %>%
  ggplot(aes(x=average_rating)) +
  geom_segment(aes(x = 0, xend = average_rating, y = decade, yend = decade), size = 2, color = "firebrick") +
  ggimage::geom_image(aes(x = average_rating, y = decade, image=img), size=0.06) +
  #scale_color_gradient(low = "darkolivegreen2", high = "darkolivegreen4", labels = scales::comma)+
  geom_text(aes(x=0.2, y=decade, label = primary_title_2), hjust=0, vjust = -0.7, family = "Gaegu", color ="black")+
  scale_x_continuous(breaks = c(2, 4, 6, 8, 10), expand = c(0.01, 0), limits = c(0, 10))+
  labs(y= "Decade", x= "Average Rating (1-10)", title = "Highest Rated Holiday Movie by Decade", subtitle = "For movies with at least 500 votes on IMDb", caption = "Erin Franke | Data Source: Internet Movie Database")+
  theme(plot.title = element_text(color = "darkgreen", face="bold"))
```

