---
title: "Tidy Tuesday Week 24"
author: "Erin Franke"
date: "6/8/2021"
output:
  html_document:
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

Load libraries and data
```{r}
library(readr)
library(tidyverse)
library(lubridate)
library(ggthemes)
library(scales)
fishing <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-08/fishing.csv')
stocked <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-06-08/stocked.csv')
options(scipen = 999)
```

**Question: How have the amount of trout stocked to the Great Lakes changes overtime, and to what lakes are each species being stocked?**
```{r}
stocked %>%
  filter(SPECIES %in% c("BKT", "BNT", "LAT", "RBT"), 
         LAKE %in% c("HU", "ER", "MI", "ON", "SU")) %>%
  group_by(SPECIES, YEAR, LAKE) %>%
  summarize(year_total = sum(NO_STOCKED, na.rm = TRUE)) %>%
  mutate(year_total = round(year_total/1000000, 1), 
         LAKE = recode(LAKE, "ER" = "Erie", "HU" = "Huron", "MI" = "Michigan", "ON" = "Ontario", "SU" = "Superior"), 
         SPECIES = recode(SPECIES, "BKT" = "Brook Trout", "BNT" = "Brown Trout", "LAT" = "Lake Trout", "RBT" = "Rainbow Trout")) %>%
  rename(`Species` = `SPECIES`) %>%
  ggplot(aes(x=YEAR, y=year_total, color = Species)) + 
  geom_line() + 
  labs(title = "Trout (millions) stocked to the Great Lakes yearly", x = "", y = "", caption = "Plot created by Erin Franke, data from Great Lakes Fishery Commission") +
  scale_y_continuous(labels = comma_format(big.mark = ",", decimal.mark = ".")) + 
  facet_wrap(~LAKE, ncol =3, scale = "free_y")+
  theme_minimal() + 
  scale_color_colorblind()+ 
  theme(legend.position = c(1, 0),
        legend.justification = c(1, 0), 
        plot.title = element_text(size = 15))
```


