---
title: "Tidy Tuesday Week 29"
author: "Erin Franke"
date: "7/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r, data and libraries}
library(tidyverse)
library(lubridate)
library(janitor)
library(ggthemes)
library(ggtext)
library(ggridges)
library(patchwork)
scoobydoo <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-13/scoobydoo.csv')
```

Clean the data
```{r}
scoobydoo$imdb <- as.numeric(scoobydoo$imdb)
scoobydoo$date_aired <- as.Date(scoobydoo$date_aired)
scoobydoo$scrappy_doo <- as.character(scoobydoo$scrappy_doo)

scoobydoo <- scoobydoo %>%
  mutate(great_rating = imdb > 7.9) %>%
  filter(!is.na(great_rating)) %>%
  select(series_name:run_time, great_rating, everything())
```

The top 91 rated scooby doo episodes...what makes them special?
```{r}
#plot one 
plot1 <- scoobydoo %>%
  ggplot(aes(x=date_aired, y=great_rating, fill = great_rating)) +
  geom_density_ridges(color = "gray60")+
  scale_fill_manual(values = c("navy", "goldenrod3"))+
  labs(x = "", y = "", title = "What makes the <strong><span style='color:goldenrod3'>91 best Scooby Doo episodes</span></strong></b> (8+ imdb) stand out from the <strong><span style='color:navy'> 497 other episodes</span></strong></b>?",
       subtitle = "They generally aired around 1970 and in the 2010s", 
       fill = "")+
  scale_x_date(breaks = as.Date(c("1960-01-01", "1970-01-01", "1980-01-01", "1990-01-01", "2000-01-01", "2010-01-01", "2020-01-01")), labels = c("1960", "1970", "1980", "1990", "2000", "2010", "2020"))+
  scale_y_discrete(expand = c(0,0)) +
  theme_minimal()+
  theme(legend.position = "none",
        plot.title.position = "plot", 
        plot.title = element_markdown(family = "mono", face = "bold", size = 9),
        plot.subtitle = element_text(family = "mono", face = "bold", size = 8),
        panel.grid.major.x = element_blank(), 
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.y = element_blank(), 
        axis.text.x = element_text(family = "mono", face = "bold"))

#plot 2
plot2 <- scoobydoo %>%
  ggplot(aes(x=run_time, y=great_rating, fill = great_rating)) +
  geom_boxplot()+
  scale_fill_manual(values = c("navy", "goldenrod3"))+
  labs(x= "", y="", title = "Almost all have a run time of about 21 minutes")+
  theme_minimal()+
  theme(legend.position = "none",
        plot.title.position = "plot", 
        plot.title = element_text(family = "mono", face = "bold", size = 8),
        panel.grid.major.x = element_blank(), 
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.y = element_blank())

#plot3
plot3 <- scoobydoo %>%
  mutate(scrappy_doo = recode("TRUE" = "Scrappy Doo in episode", scrappy_doo, "FALSE" = "NO Scrappy Doo")) %>%
  ggplot(aes(x=scrappy_doo, fill = great_rating))+
  geom_bar(position = "fill")+
  scale_fill_manual(values = c("navy", "goldenrod3"))+
  labs(x="", y="", title = "Scrappy Doo usually does not appear in the episode")+
  theme_minimal()+
  theme(legend.position = "none",
        plot.title.position = "plot", 
        plot.title = element_text(family = "mono", face = "bold", size = 8),
        panel.grid.major.x = element_blank(), 
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(),
        axis.text.y = element_blank())+
  annotate(geom="text",x="Scrappy Doo in episode", y=0.5,label="out of the 165 times \nScrappy Doo was in \nthe episode, only 3 \nreceived an 8+ rating", family = "mono", fontface="bold", cex = 2.5, color = "white")
```


```{r, echo = FALSE}
plots_together <- (plot1) / 
      (plot2 | plot3)
plots_together + plot_annotation(
  caption = "Erin Franke, data credit to Kaggle and plummye")
```

