---
title: "Tidy Tuesday Week 28"
author: "Erin Franke"
date: "7/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r data and libraries}
library(tidyverse)
library(rvest)
library(httr)
library(polite)
library(lubridate)
library(janitor)
library(ggridges)
library(ggthemes)
library(lubridate)
holidays <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-07-06/holidays.csv') #after loading data, cleaned it using Isabel Velasquez cleaning script
```
```{r clean data, echo = FALSE}
# Scrape data -------------------------------------------------------------

url <- "https://en.wikipedia.org/wiki/List_of_national_independence_days"
url_bow <- polite::bow(url)

ind_html <-
  polite::scrape(url_bow) %>%
  rvest::html_nodes("table.wikitable") %>%
  rvest::html_table(fill = TRUE)

ind_tab <-
  ind_html[[1]][1:6] %>%
  as_tibble() %>%
  clean_names()

# Clean data --------------------------------------------------------------

holidays <-
  ind_tab %>%
  # Cleaning up some dates
  mutate(
    date_of_holiday = case_when(
      country == "Croatia" ~ "May 30",
      country == "Mexico" ~ "September 16",
      country == "Mongolia" ~ "December 29",
      country == "Paraguay" ~ "May 14",
      country == "Israel" ~ "May 14", # Independence Day exists within a range, but this was the original date.
      country == "Slovenia" ~ "June 25", # Slovenia has two dates; this one is "Statehood Day".
      TRUE ~ date_of_holiday
    ),
    year = str_sub(year_of_event, start = 1, end = 4),
    date_mdy = case_when(
      date_of_holiday != "" ~ paste0(date_of_holiday, ", ", year),
      TRUE ~ ""
    ),
    date_parsed = mdy(date_mdy),
    weekday = weekdays(date_parsed),
    day = day(date_parsed),
    month = month(date_parsed, label = TRUE),
    year_of_event = as.integer(year_of_event),
    year = as.integer(year)
  ) %>%
  relocate(date_parsed:month, .after = country)
```

```{r}
allied_holidays <- holidays %>%
  filter(independence_from %in% c("Egypt and the United Kingdom, Empire of Japan and France", "France", "France and Spain", "Italy and United Kingdom", "Kingdom of Great Britain", "Soviet Union", "Soviet Union[55]", "Soviet Union[80]", "United Kingdom", "United Kingdom and France", "United Kingdom and the British Mandate for Palestine", "United Kingdom of Great Britain and Ireland", "United Kingdom of Portugal, Brazil and the Algarves", "United States")) %>%
  mutate(allied_group = case_when(
    independence_from %in% c("Egypt and the United Kingdom", "Italy and United Kingdom", "Kingdom of Great Britain", "United Kingdom and France", "United Kingdom", "United Kingdom and the British Mandate for Palestine", "United Kingdom of Great Britain and Ireland", "United Kingdom of Portugal, Brazil and the Algarves") ~ "United Kingdom", 
    independence_from %in% c("Empire of Japan and France", "France", "France and Spain", "United Kingdom and France") ~ "France", 
    independence_from %in% c("Soviet Union", "Soviet Union[55]", "Soviet Union[80]") ~ "Soviet Union", 
    independence_from == "United States" ~ "United States"
  )) %>%
  group_by(allied_group, date_parsed)%>%
  count()%>%
  ungroup() %>%
  group_by(allied_group)%>%
  mutate(cum_indepfrom = cumsum(n))
```

```{r}
allied_holidays %>%
  filter(allied_group %in% c("France", "Soviet Union", "United Kingdom")) %>%
  filter(date_parsed > "1940-01-01") %>%
  ggplot(aes(x=date_parsed, y=allied_group, fill = allied_group)) +
  geom_density_ridges(color = "gray60") +
  scale_fill_manual(values = c("darkred", "goldenrod3","navy"))+
  labs(x = "", y = "", 
       title = "Countries gaining independence from Allied Powers after 1940", 
       fill = "",
       caption = "Erin Franke | Data from Wikipedia, cleaned by Isabel Velasquez")+
  scale_y_discrete(expand = c(0,0)) +
  scale_x_date(breaks = as.Date(c("1940-01-01", "1950-01-01", "1960-01-01", "1970-01-01", "1980-01-01", "1990-01-01", "2000-01-01", "2010-01-01")), labels = c("1940", "1950", "1960", "1970", "1980", "1990", "2000", "2010"))+
  theme_minimal()+
  theme(legend.position = "none",
        plot.title.position = "plot", 
        plot.title = element_text(family = "mono", face = "bold", size = 13),
        panel.grid.major.x = element_blank(), 
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.text.y = element_blank(), 
        axis.text.x = element_text(family = "mono", face = "bold"), 
        plot.caption = element_text(family = "mono"))+
  annotate(geom="text",x=as.Date("1945-12-15"), y=3.33,label="Great Britain", family = "mono", fontface="bold", cex = 3.3)+
  annotate(geom="text",x=as.Date("1980-09-15"), y=2.1,label="Soviet Union", family = "mono", fontface="bold", cex = 3.3)+
  annotate(geom="text",x=as.Date("1945-01-10"), y=1.25,label="France", family = "mono", fontface="bold", cex = 3.3)+
  geom_curve(aes(x = as.Date("1952-07-01"), y = 2.5, xend = as.Date("1959-06-01"), yend = 2.25),arrow = arrow(length = unit(0.03, "npc")), curvature = -0.4, color = "darkred")+
  annotate(geom="text",x=as.Date("1944-09-15"), y=2.5,label="17 countries gain \nindependence in The Year \nof Africa, 13 from France", family = "mono", fontface="bold", cex = 3, color = "darkred")+
  annotate(geom="text",x=as.Date("1985-08-15"), y=3.55,label="Soviet Union \ncollapses, 13 \ncountries gain \nindependence", family = "mono", fontface="bold", cex = 3, color = "goldenrod3")
```
