---
title: "Tidy Tuesday Week 33"
author: "Erin Franke"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(tidyverse)
investment <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/investment.csv')
chain_investment <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/chain_investment.csv')
ipd <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-08-10/ipd.csv')
```

```{r}
chain_investment %>%
  filter(meta_cat == "Air /water /other transportation") %>%
  mutate(decade = as.factor(cut(year, 
                      breaks = c(1940, 1950, 1960, 1970, 1980, 1990, 2000, 2010, 2020), 
                      labels = c("1940s", "1950s", "1960s", "1970s", "1980s", "1990s", "2000s", "2010s")))) %>%
  group_by(decade,category) %>%
  summarize(cat_spending = sum(gross_inv_chain)) %>%
  group_by(decade) %>%
  mutate(cat_rank = rank(-cat_spending), 
         decade_total = sum(cat_spending), 
         prop_of_decade = round(100*(cat_spending / decade_total),2)) %>%
  filter(cat_rank <= 3) %>%
  mutate(decade_total_prop = sum(prop_of_decade)) %>%
  ggplot(aes(x=decade, y=decade_total_prop/3, fill = category))+
  geom_col(color = "white") +
  theme_minimal()+
  scale_fill_manual(values = c("lightcoral", "plum3", "seashell3", "palegreen3", "paleturquoise3", "sandybrown", "orchid2", "yellow2", "steelblue2", "tan1", "royalblue2", "palevioletred2"))+
  labs(x="", y="", 
       title = "Share of US air/water/other transportation spending by top 3 categories per decade", 
       subtitle = "Calculated with BEA gross investment chained in 2021 dollars", 
       caption = "Erin Franke, data courtesy of BEA")+
  annotate(geom = "text", x = "1940s", y = 75, label = "Other \nfederal \nstructures", family= "mono", color = "black", cex = 2.5, face = "bold")+
  annotate(geom = "text", x = "1950s", y = 40, label = "S&L air \ntransportation \nstructures", family= "mono", color = "black", cex = 2, face = "bold")+
  annotate(geom = "text", x = "1950s", y = 15, label = "S&L water \ntransportation \nstructures", family= "mono", color = "black", cex = 2, face = "bold")+
  annotate(geom = "text", x = "1980s", y = 15, label = "Transit", family= "mono", color = "black", cex = 2.5, face = "bold")+
  annotate(geom = "text", x = "1990s", y = 35, label = "S&L local \ntransit \nstructures", family= "mono", color = "black", cex = 2.5, face = "bold")+
  annotate(geom = "text", x = "1960s", y = 53, label = "Private \nrailroad & \ntrack \nreplacement \nstructures", family= "mono", color = "black", cex = 2, face = "bold")+
  theme(legend.position = "none", 
        panel.grid.major.x = element_blank(), 
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_blank(),
        panel.grid.minor.y = element_blank(), 
        plot.title.position = "plot", 
        plot.title = element_text(family= "mono", color = "black", size=10, face = "bold"), 
        plot.subtitle = element_text(family= "mono", color = "black", size=9, face = "bold"), 
        axis.text = element_text(family= "mono", color = "black", size=8, face = "bold"), 
        plot.caption = element_text(family= "mono", color = "black", size=8, face = "bold"))
```

